remove.packages('shiny')
remove.packages('foreign')
remove.packages('data.table')
remove.packages('gridGraphics')
remove.packages('xlsx')
remove.packages('rmarkdown')
remove.packages('plyr')
remove.packages('EBImage')

install.packages('shiny')
install.packages('foreign')
install.packages('data.table')
install.packages('gridGraphics')
install.packages('xlsx')
install.packages('rmarkdown')
install.packages('plyr')
source("http://bioconductor.org/biocLite.R")
biocLite("EBImage")